name: mlate2dge
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3.1
  - jupyterlab=3.5.0
  - pandas=1.5.2
  - pyyaml=6.0
  - matplotlib=3.6.2
  - bokeh=3.0.2
  - pingouin=0.5.2
  - tensorflow=2.10.0
  - numba=0.56.4
  - pip:
    - wandb==0.12.20
    - netron==7.1.4